<?php

return [
    'articles' => [
        [
            'slug' => 'costata-alla-fiorentina',
            'title' => 'Costata alla Fiorentina perfetta',
            'excerpt' => 'Selezione della carne, temperatura e riposo: la guida rapida alla bistecca alta.',
            'content' => 'Per una fiorentina perfetta servono taglio alto, brace viva e pochi movimenti. Porta la carne a temperatura ambiente, sala solo dopo la cottura e lasciala riposare almeno 8 minuti prima del taglio. Risultato: crosta intensa, cuore succoso e profumo affumicato equilibrato.',
            'image' => 'https://source.unsplash.com/1600x900/?grilled-steak,bbq&sig=1',
            'category' => 'Bovino',
            'read_time' => '6 min',
        ],
        [
            'slug' => 'hamburger-smash-home',
            'title' => 'Smash burger su piastra rovente',
            'excerpt' => 'Tecnica smash, doppia crosticina e panino morbido: equilibrio perfetto in casa.',
            'content' => 'Lo smash burger si gioca tutto nei primi 30 secondi: palla da 100 g, piastra caldissima e pressione decisa. Gira una sola volta, aggiungi cheddar e chiudi nel bun tostato. Condimenti semplici per lasciare protagonista la carne.',
            'image' => 'https://source.unsplash.com/1600x900/?smash-burger,grill&sig=2',
            'category' => 'Street Grill',
            'read_time' => '5 min',
        ],
        [
            'slug' => 'costine-low-and-slow',
            'title' => 'Costine low & slow',
            'excerpt' => 'Rub aromatico, cottura indiretta e glassa finale per costine morbide.',
            'content' => 'Le costine rendono al massimo con cottura indiretta a bassa temperatura. Usa un rub bilanciato, vaporizza ogni tanto e termina con glassatura leggera negli ultimi minuti. La carne deve staccarsi al morso senza sfaldarsi.',
            'image' => 'https://source.unsplash.com/1600x900/?bbq-ribs,grill&sig=3',
            'category' => 'Maiale',
            'read_time' => '7 min',
        ],
        [
            'slug' => 'spiedini-misti-estivi',
            'title' => 'Spiedini misti per serate estive',
            'excerpt' => 'Pollo, manzo e verdure con marinature leggere e cotture differenziate.',
            'content' => 'Per spiedini bilanciati combina tagli con tempi simili oppure separali per tipo. Marinatura breve con olio, limone e spezie, poi cottura in zona diretta e finitura dolce-piccante. Servili con salsa yogurt e erbe fresche.',
            'image' => 'https://source.unsplash.com/1600x900/?meat-skewers,barbecue&sig=4',
            'category' => 'Misti',
            'read_time' => '4 min',
        ],
        [
            'slug' => 'petto-pollo-grigliato-succoso',
            'title' => 'Petto di pollo tenero e succoso',
            'excerpt' => 'Brining veloce e cottura controllata per dire addio al pollo secco.',
            'content' => 'Il segreto del pollo succoso è il brining: 30 minuti in acqua e sale, asciugatura e griglia media. Gira spesso per evitare zone secche e termina con un filo d’olio aromatizzato. Riposo breve e taglio controfibra.',
            'image' => 'https://source.unsplash.com/1600x900/?grilled-chicken,bbq&sig=5',
            'category' => 'Pollo',
            'read_time' => '5 min',
        ],
        [
            'slug' => 'salsiccia-e-brace-gestione-grassi',
            'title' => 'Salsiccia e gestione dei grassi',
            'excerpt' => 'Come evitare fiammate aggressive e mantenere la salsiccia ben cotta.',
            'content' => 'Le salsicce richiedono controllo: inizia in zona indiretta e passa alla rosolatura finale. Buchi no, per non perdere succhi. Quando la superficie è uniforme e la temperatura interna è corretta, servi subito con pane rustico.',
            'image' => 'https://source.unsplash.com/1600x900/?sausage,grill&sig=6',
            'category' => 'Maiale',
            'read_time' => '4 min',
        ],
        [
            'slug' => 'tagliata-rucola-grana',
            'title' => 'Tagliata con rucola e grana',
            'excerpt' => 'Cottura rapida ad alta temperatura e affettatura precisa controfibra.',
            'content' => 'La tagliata richiede piastra rovente e tempi rapidi. Sigilla bene l’esterno, lascia riposare e affetta sottile in diagonale. Completa con rucola, scaglie di grana e riduzione balsamica per contrasto fresco e sapido.',
            'image' => 'https://source.unsplash.com/1600x900/?beef-steak,sliced&sig=7',
            'category' => 'Bovino',
            'read_time' => '5 min',
        ],
        [
            'slug' => 'brisket-affumicato-base',
            'title' => 'Brisket affumicato: base essenziale',
            'excerpt' => 'Metodo base per una punta di petto morbida con bark intenso.',
            'content' => 'Il brisket richiede pazienza: fuoco stabile, fumo pulito e riposo lungo. Mantieni umidità costante e avvolgi al momento giusto per superare lo stallo. Affetta sottile per esaltare morbidezza e sapore affumicato.',
            'image' => 'https://source.unsplash.com/1600x900/?smoked-brisket,bbq&sig=8',
            'category' => 'BBQ Classico',
            'read_time' => '8 min',
        ],
        [
            'slug' => 'agnello-alla-brace-erbe',
            'title' => 'Agnello alla brace con erbe',
            'excerpt' => 'Rosmarino, aglio e limone per un agnello profumato e bilanciato.',
            'content' => 'Per l’agnello usa marinatura breve con erbe mediterranee e cottura media. Evita temperature eccessive per non indurire le fibre. Una salsa verde fresca a lato valorizza la dolcezza naturale della carne.',
            'image' => 'https://source.unsplash.com/1600x900/?lamb,grill&sig=9',
            'category' => 'Agnello',
            'read_time' => '6 min',
        ],
        [
            'slug' => 'picanha-alla-brasiliana',
            'title' => 'Picanha in stile brasiliano',
            'excerpt' => 'Taglio iconico, sale grosso e cottura semplice ma precisa.',
            'content' => 'La picanha si cuoce in tranci spessi con il grasso verso la fonte di calore. Sale grosso, fuoco deciso e riposo finale per ottenere succosità e crosta aromaticamente intensa. Servi a fette sottili con chimichurri.',
            'image' => 'https://source.unsplash.com/1600x900/?picanha,barbecue&sig=10',
            'category' => 'Bovino',
            'read_time' => '6 min',
        ],
    ],
];
